#exception-handling
#try except
#
# num1=int(input('enter the num1'))
# num2=int(input('enter the num2'))
# try:
#     print(num1/num2)      #try block is given to the line which there is any possibility of unexpected errors
# except Exception as Error:      #exception is a module Error is variable to call exception
#     print(Error)


# l=[1,2,3]
#
# try:
#     index = int(input('enter index'))
#     print(l[index])
# except Exception as E:
#     print(E)

